# Generated by Django 4.2.7 on 2023-12-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name': 'کد تایید کاربر'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر'},
        ),
    ]
