# Generated by Django 4.2.7 on 2023-12-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpcode_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name': 'کد تایید کاربرها'},
        ),
    ]
