# Generated by Django 4.2.7 on 2023-12-03 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('translator', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=200)),
                ('data_of_release', models.DateField()),
                ('name_orginal', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=200)),
                ('price_Electric', models.IntegerField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_electric_available', models.BooleanField()),
                ('is_printed_available', models.BooleanField()),
                ('publisher', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('print_series', models.CharField(max_length=30)),
                ('number_of_pages', models.IntegerField()),
                ('ISBN', models.IntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvote', to='home.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_replay', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcommmnt', to='home.book')),
                ('repley', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='home.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucomment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
