# Generated by Django 4.2.7 on 2023-12-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'کتاب'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'رای'},
        ),
    ]
