# Generated by Django 4.2.7 on 2023-12-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_book_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(null=True, verbose_name='شابک'),
        ),
        migrations.AlterField(
            model_name='book',
            name='autor',
            field=models.CharField(max_length=200, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=200, verbose_name='ژانر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد موجودی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='credits',
            field=models.IntegerField(null=True, verbose_name='تیراژ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='data_of_release',
            field=models.DateField(null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='نصویر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_electric_available',
            field=models.BooleanField(verbose_name='موجودیت نسخه الکتریکی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_printed_available',
            field=models.BooleanField(verbose_name='موجودیت نسخه چاپی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=200, verbose_name='ربان کتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم کتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_orginal',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم اصلی کتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(verbose_name='تعداد صفحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(null=True, verbose_name='قیمت نسخه چاپی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_Electric',
            field=models.IntegerField(null=True, verbose_name='قیمت نسخه الکتریکی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='print_series',
            field=models.CharField(max_length=30, null=True, verbose_name='نوبت چاپ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=200, null=True, verbose_name='ناشر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(max_length=200, null=True, verbose_name='مترجم'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcommmnt', to='home.book', verbose_name="<class 'home.models.Book'>"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucomment', to=settings.AUTH_USER_MODEL, verbose_name="<class 'accounts.models.User'>"),
        ),
        migrations.AlterField(
            model_name='vote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvote', to='home.book', verbose_name="<class 'home.models.Book'>"),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvote', to=settings.AUTH_USER_MODEL, verbose_name="<class 'accounts.models.User'>"),
        ),
    ]
