# Generated by Django 4.2.7 on 2023-12-04 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_book_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'کتاب '},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظرات '},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'رای '},
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcommmnt', to='home.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_replay',
            field=models.BooleanField(default=False, verbose_name='ریپلای  نظر دیگری'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='repley',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='home.comment', verbose_name='ریپلای'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucomment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvote', to='home.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvote', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
