# Generated by Django 4.2.7 on 2023-12-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_book_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=50, verbose_name='ژانر'),
        ),
    ]
